### ISSUE TITLE
Make MultiTV compatible with ManagerManager

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#107]
Hi, to make ManagerManager work with MultiTV, there is currently the need to apply the following patch: open the file mm.inc.php and insert case 'custom_tv': in line 136 just before the line $t = 'textarea'; (see here, step 4 for the installation: https://github.com/Jako/multiTV).

This fix is kind of dangerous because it could break a website anytime you update the CMS. Is it possible to add this to ClipperCMS, or is this some kind of hack to the system? Would it work for all Custom Template Variables?

**Comment by TimGS** [comment]
It's arguable where the issue lies. I'm not familiar with MultiTV but I'm guessing it adds a new TV type - but there is no provision in the core (AFAIK) for adding another TV type. As such, the hack may be in MultiTV itself and be an inherent part of how it works.

Any Extra that 'adds' another TV type will have the same problem with ManagerManager, or indeed any other plugin that assumes the TV types are finite.

-- Tim.

**Comment by Eoler** [comment]
There's an official "custom" TV type in core, as of Evolution 1.0.5

**Comment by TimGS** [comment]
OK. We best add it in then.

**Comment by Jako** [comment]
Any custom TV that will use a textarea tag to avoid of issues with " and ' chars in the custom TV value will have a problem with ManagerManager. This custom TV will be not moveable to other Tabs without the patch. But that should be the only problem.

My proposal is to patch ManagerManager and to tell other custom TV developers to change input to textarea.

**Comment by TimGS** [comment]
I agree we should add line 136 as above to cope with custom tvs now they are an option in the core. 

I'm not familiar with custom tvs - what's the textarea issue about? I'm wary of getting into hacky territory. Why do custom tv developers need to avoid inputs?

**Comment by Jako** [comment]
If a custom tv has " and ' chars inside one of this chars has to be masked to be valid in the value attribute of an input tag. Otherwise it will break the value tag. Another problem would be the new line char.

Instead of masking/demasking the field value I decided to change the input tag to textarea tag. But that is causing the problem with ManagagerManager.

**Comment by TimGS** [comment]
That seems a hack to me. Shouldn't the output snippet (I think this is the MultiTV snippet) pass characters through htmlentities (or better, have the _option_ to with 'on' as the default) ?

-- Tim.

**Comment by Jako** [comment]
This is not a snippet output problem and it is definitly not a hack since normal textarea and richtext (and some other) template variables work the same.

The MODX/ClipperCMS Manager saves the value of a tv during a form post. At this point the custom tv code is **not** invoked and can't work the value of the tv. The custom tv code just outputs the form code together with javascripts and style sheets. And it could be possible that the value of the custom tv breaks the input tag. That could not happen with the textarea tag, so I decided to use that form field type.

The only problem is that ManagerManager was written before custom tvs were introduced and the javascript code uses                           the form field type to identify the template variable if it should be moved to another tab in line 274 of fields.inc.php

`var toMove = $j("'.$fieldtype.'[name='.$fieldname.']").parents("tr:not(.urltv)"); // Identify the table row to move`

What kind of form field type custom tvs should be is documented nowhere. In my opinion a textarea form field is better because this avoids some problems and creates no masking/demasking overhead in the custom tv javascript code.

**Comment by TimGS** [comment]
OK - I'm not sure I really follow the textarea/input thing but I'm not familiar with custom tvs.

I agree we should add line 136 as above to cope with custom tvs now they are an option in the core. Do we need to do anything else at the moment?

I think the issue of custom TVs needs discussing on the forum. If someone who is familiar with them can write a brief resume of any documentation, extras using them, sample applications that would be useful.

Also essential from the point of view of development is for someone to document how custom tvs are stored internally - i.e. how do they shoehorn multiple TVs into one database entry? It may well be worth considering an alternative - we can modify the core now. Storing multiple values in one db row is not ideal.

**Comment by Jako** [comment]
multiTV values are stored as JSON in one db row. multiTV is not intended to be a solution to hold a lot of data. For that it would be ideal to have a custom tv displaying/saving tabular data in its own db table. But that needs a different approach with own processors/connectors to read/save the data.

The main reason to write multiTV was to store object properties for a small shop solution. Also slider images, small document based galleries, link lists and downloads would fit good into a multiTV. Everything that is too small to use MODX/ClipperCMS documents and Ditto/List for.

**Comment by microcipcip** [comment]
Maybe this could help:
http://thecmspros.com/2011/02/custom-template-variables-in-evolution-1-5/
http://www.mapledesign.co.uk/projects/modx-tvs/

**Comment by TimGS** [comment]
Fixed by https://github.com/ClipperCMS/ClipperCMS/commit/d6a5ed1b2e9d76e7981f7056dbfc6632ef85df39

Note that it's not line 136 anymore as other things have changed in that file.

If someone with a site using custom tvs and managermanager can test this then I'll close the issue.

**Comment by microcipcip** [comment]
This is working, I have tested the latest version of MultiTV.
