### ISSUE TITLE
System Setting "Page Click Behavior" default to "Edit Resource"

### ISSUE THREAD

**Issue by microcipcip** [ClipperCMS/ClipperCMS#113]
When you install ClipperCMS by default you see the "Page Click Behavior" found in "Tools > Configuration > Interface & Features" with the radio button on " View Resource data" instead of "Edit Resource". 

I never use "View Resource data", it seems a waste of time to click a resource and then click on "Edit" to actually edit the page. I would like to know how other people use this setting and discuss if it would be better to set it by default to "Edit Resource".

Note: on previous version of MODX Evolution this setting was on "Edit Resource", I believe that it was changed in the last two version  of the CMS, and I have never understood why.

**Comment by nick0** [comment]
I also prefer "Edit Resource" by default microcipcip - its much more efficient and better for workflow to be able to edit a resource directly. I second we have that as the default setting.

Re your note: In Evo 1.0.6 and 1.0.7, setting "Page Click Behavior" to "Edit Resource" still works as the default behavior for me.

Go ClipperCMS!

**Comment by bossloper** [comment]
I use both, depending upon the project. For a single manager of a site (mainly me!) I use the "Edit Resource" option for efficiency.

Though for a large site with maybe 20 managers I use the "View Resource data" option when it goes live. Main reason being otherwise the site tends to get locked resources from time to time as less careful managers just close the browser on the last resource they clicked on, regardless of if they actually wanted to edit it! Also with a large multi-manager site it gives better manager log data to indicate someone actually wanted to edit a resource. Otherwise the lazy sometimes just click save even if they did not make a change.

I suppose it is quite none-standard for an computer interface that a single click on an item would result in editing it, though does speed things up! Don't think it is a big deal whichever is default.

**Comment by kp52** [comment]
I'm all for making Edit Resource the set-up default. One of the annoying things setting up something new is having to go back and change it when I realize I didn't do it in the first place. Likewise the "remember tab" settings just below it in config.

**Comment by microcipcip** [comment]
Likewise the "remember tab" settings just below it in config. +1

**Comment by TimGS** [comment]
Implemented.

https://github.com/ClipperCMS/ClipperCMS/commit/9f9e066e0c5f27ca80725354adbff1e513f0a3e9
