### ISSUE TITLE
Error reporting again or the lack of ...

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#132]
I recently merged the latest develop branch into my jquery-ui branch and errors are not reported.

Here's are some details:
Config: 
- How should deprecated PHP functions be handled (PHP >= 5.3): Allow deprecated functions. Log under Reports, System Events
- Should PHP/SQL error messages be shown on the screen: Show on screen

PHP Version 5.4.4 - MAMP

Create a snippet with the following code and call it somewhere in the document

```
<?php
aaaa
return fsdfs
?>
```

The code above should generate some errors either on screen either in the System Events but in my case everything is clean.

Can you/someone please try this on a similar setup. Maybe it's just me.

Thanks

**Comment by TimGS** [comment]
Same happens here with PHP 5.3. It also happens with 1.0.6.

However see the PHP manual - http://php.net/manual/en/function.eval.php. _"It is not possible to catch a parse error in eval() using set_error_handler()"_

As such, that is the expected behaviour at the moment. We could modify the DocumentParser class to test for eval() returning false, which would catch parse errors.

**Comment by Cipa** [comment]
This would be nice. Can the error be caught somehow and actually be reported in the system events?

Thank you

**Comment by Cipa** [comment]
Another thing I noticed is that if I change the database credentials to something wrong the errors are showed on screen but no System event is generated. Is this correct?

What I need right now is a way to generate some errors in the System Events. I can't seem to do it(modified snippets, files plugins and no errors are reported). Maybe you have an idea on how to do it.

Thanks

Edit:

Seems like older versions of modx(tested on 1.5RC) generate a system event if DocManager is modified to have errors. The same thing doesn't happen on the develop branch.. Can you confirm?

**Comment by TimGS** [comment]
re: Parse errors. These could be caught if the code was changed to check for this. It's only likely to be relevant for development though - live sites shouldn't be generating parse errors.

re: database credentials. Nothing can be added to the error log in this case because the error log is in the database - which is inaccessible!

re: deliberately generating errors. Offhand, deprecated functions and SQL errors definitely result in errors. See also http://php.net/manual/en/errorfunc.constants.php. The following should produce an error in the log:

E_ERROR
E_WARNING - maybe, not 100% sure
E_COMPILE_ERROR
E_COMPILE_WARNING
E_USER_ERROR
E_USER_WARNING
E_USER_NOTICE
E_STRICT (I think just in PHP 5.4)
E_RECOVERABLE_ERROR
E_DEPRECATED (PHP 5.3+)
E_USER_DEPRECATED (PHP 5.3+)

re: modules. The module code was changed in 1.1 to bring it into line with the error reporting in the rest of the system, so I think what you are seeing is that E_PARSE is no longer caught, as per snippets and plugins.

-- Tim.

**Comment by TimGS** [comment]
Parse errors now caught. See #188
