### ISSUE TITLE
messaging system - remove updateMsgCount ajax call

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#134]
If the messaging system was completely removed we should also remove the ajax call that updates the message count.

Look for updateMsgCount. There should be only 2 files that have this: main-menu.js and manager/index.php

**Comment by Cipa** [comment]
updateMail function should also be removed. I will remove this from my jQuery branch as soon I get the conformation that this is ok.

**Comment by TimGS** [comment]
On branch develop I have:
- removed updateMail https://github.com/ClipperCMS/ClipperCMS/commit/8b06a598b83753fb7997398815ca3c5ea7c33c63
- removed one reference to $_POST['updateMsgCount'] in manager/index.php https://github.com/ClipperCMS/ClipperCMS/commit/75df0bd6ecb98cf4c1dfbef744c1533f9712cdef

I can't find main-menu.js (puzzled?!)

To merge these changes into your jquery branch either use git merge or git rebase. I don't really know enough about git to be sure, but as your jquery branch is not in the main ClipperCMS repo, and so because only you probably have a copy, then git rebase may be better. Probably worth reading up on this.

Alternatively you should be able to pull these changes into your local copy of develop, and then just cherry-pick these two commits into your jquery branch.

-- Tim.

**Comment by Cipa** [comment]
not sure about main-menu.js but it looks like I moved some of the code in that file. 
The changes look good. I will remove the code from the jquery-ui branch - https://github.com/Cipa/ClipperCMS/tree/jquery-ui

**Comment by TimGS** [comment]
You are best either merging, rebasing (maybe) or cherry-picking my commits - as opposed to doing it manually in your jquery branch -  otherwise when we merge your jquery branch into develop we may end up with commits duplicating each other.

**Comment by TimGS** [comment]
I think this should work:

git checkout develop
git pull
git pull upstream develop

You should now have develop up to date locally, assuming you have ClipperCMS/ClipperCMS as the remote 'upstream'.

git checkout jquery-ui
git cherry-pick 8b06a59
git cherry-pick 75df0bd

This will just fetch the above two commits.

**Comment by Cipa** [comment]
I will do that but in order to keep conflicts to a minimum and because I
already moved/changed to jquery some of the code, I will remove those parts
first and merge after

**Comment by TimGS** [comment]
Whatever you think best, but I think you'll end up with duplicate commits when we merge jquery-ui into develop. Mine will still appear, but yours will also. Probably not a big deal though [EDIT - not so sure about this now]

git seems quite good at this - loads better than SVN if you've had previous bad experience with SVN conflicts.

Happy New Year for later on! Bye for now.

**Comment by Cipa** [comment]
Happy new year!

**Comment by Cipa** [comment]
mail_check_timeperiod should also be removed
There are a few files using it including setup sql and language files

**Comment by TimGS** [comment]
See https://github.com/ClipperCMS/ClipperCMS/commit/eacba5cdd5cdf9af66356a8a0a1be2ab956229ff

and https://github.com/ClipperCMS/ClipperCMS/commit/50ba4107c1a5133245be33513dc945241bbe8c39.

**Comment by Cipa** [comment]
Thanks, lately it seem that I am getting a lot of conflicts on some files
I modified a lot. It happend for mutate_settings.
Can you make sure all your changes where implemented and also have a look
at my changes regarding this issue
https://github.com/Cipa/ClipperCMS/commit/4c50c17a8d2e873aad2e2e79c2338b36bb6ca386

Latest commits for jquery-ui branch:
https://github.com/Cipa/ClipperCMS/commits/jquery-ui

**Comment by TimGS** [comment]
You may be more likely to get conflicts if you manually duplicate commits as you are doing now. Also I'm much more likely to have conflicts (maybe lots of them) when I merge it into the main repo or accept a pull request.

Conflicts occur when two or more people have changed the same line of code but in different ways. Even an extra space character makes the code different as far as diff is concerned (as far as I can see git uses diff and hence works on a per line basis). This incidentally is why I'm against reformatting code for the sake of it - it shows up as changed code, and needs checking.

Manually duplicating changes also makes it harder for someone to review code as it needs to be reviewed twice! It would be much easier if you reverted the commits that duplicate my own changes, and then either merged or cherry picked my commits. For example, rather than implementing https://github.com/Cipa/ClipperCMS/commit/4c50c17a8d2e873aad2e2e79c2338b36bb6ca386 and me checking it - thus doubling the work required for both of us - just cherry pick my corresponding commit. I've already done the change - no point someone else doing it as well.

Cherry picking has the short term advantage that it just introduces small changes into your own branch, rather than making bigger and perhaps more confusing changes all at once. Having said that, both branches will have to be merged sometime, and the longer it's left, the bigger the job.

I'm not sure, but I think that the more often you merge (or rebase - I'm not familiar enough with git to be able to be sure, but I think rebase may be better in this case) the better, and the less likely you are to have conflicts as you are more likely to have merged changes from develop _before_ you edit the corresponding lines in jquery_ui and hence you are more likely to avoid the conflicts.

-- Tim.
