### ISSUE TITLE
TV Date Formatter widget "today if blank" fails

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#190]
Bug in manager/includes/tmplvars.format.inc.php

If you set the "If no value, use current date" field to Yes in the TV Date Formatter widget and have a blank in the TV's input, it produces the Unix epoch date 1st Jan 1970, not today's date. 

I have fixed and tested, but don't want to update the existing Pull request (https://github.com/ClipperCMS/ClipperCMS/pull/186) while it has problems.

I propose to Close that Pull request, take a fresh fork and update it with my files for #186 and the date formatter fix, then make a fresh Pull request. 
(I now know you can preview the expected outcome of a Pull; will check this in future)

**Comment by TimGS** [comment]
I have cherry-picked the correct commit for #186.

With any pull request I can view the commits and cherry-pick individual ones. I suspect this means however that your fork and the main repo are somehow 'out of step', so yes, best take a fresh fork and then submit the fix for this issue.

thanks,
-- Tim.
