### ISSUE TITLE
Collations problem with accented characters

### ISSUE THREAD

**Issue by MPerrine** [ClipperCMS/ClipperCMS#20]
When I create a new document, using an accented character in generated alias, I get this message :

`« ClipperCMS Parse Error »
ClipperCMS encountered the following error while attempting to parse the requested resource:
« Execution of a query to the database failed - Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' »
      SQL: SELECT COUNT(id) FROM `carnet_clipper`.`modx_site_content` WHERE id<>'' AND alias='la-s�lection'`

When the alias doesn't have any accented character, the creation is ok.

Collation for the database is utf8_general_ci
In Clipper manager, both language and encoding are UTF8
When I installed ClipperCMS, I selected SET NAMES UTF8 as SET CHARACTER NAME was not available with UTF8
In config fiie :
$database_connection_charset = 'utf8';
$database_connection_method = 'SET NAMES';

But, in database, I see latin1_swedish_ci as collation. I compared with an Evo 1.0.5 installation, and I also have latin1_swedish_ci as collation but I don't get this message.

**Comment by MPerrine** [comment]
Hum... further tests make me think that the problem is from TransAlias.

When I check the box «generate alias auto», I get the error message with collation.

If I uncheck this option, alias is not generated ant the document is saved.

Now, if I desactivate TransAlias, the alias is generated but without the accented characters. For the word «sélection», I get «slection» instead of «selection»

**Comment by TimGS** [comment]
Which version of MySQL?

**Comment by TimGS** [comment]
Also post the output of the following SQL:

show variables like 'char%';

show variables like 'collation%';

show full columns from modx_site_content;

You should also check the character set / collations of text/char/varchar fields in your db tables.

"Collation for the database is utf8_general_ci" and "But, in database, I see latin1_swedish_ci as collation." seem contradictory - can you elaborate? Do consider that just because the db schema's default collation is utf8, that doesn't mean that every existing column will be utf8 - it just means that new columns will default to utf8. Offhand, I think that any imports from an SQL dump (e.g. phpmyadmin export or mysqldump) will try to preserve the original char set / collation of each column regardless of the new db defaults.

This does sound like a character set problem with the database, rather than a Clipper (or MODx) issue.

**Comment by AgelxNash** [comment]
**TimGS** correctly told you - you do not select the correct encoding mapping database. But personally, I was concerned about other things. Why the text is not your fault id. 

<code>WHERE id <>''</code>

**Comment by MPerrine** [comment]
MySQL version is 5.5.9

I don't know how to output char% and collation%, what are they ? Where can I find them ?

Collation for text/char/varchar fields is latin1_swedish_ci (this is what I meant in my message with : _in database, I see latin1_swedish_ci as collation_)

Strange think is that when I save a document with accented character in pagetitle, its ok. 
The error message only comes when I generate alias with TransAlias on and with accented characters

@AgelxNash : I don't konw :/

But most important : this morning, I put TransAlias on, and the problem seems to have disapeared ! I can save a document with generated alias with and without accented characters. I can't get to reproduce the error.

**Comment by TimGS** [comment]
Go into your mysql client (or phpmyadmin) and type in the SQL (one at at a time):

show variables like 'char%';

show variables like 'collation%';

show full columns from modx_site_content;

I recommend that if your site is utf-8 (which is wise) you also change your db fields to utf8 (otherwise you cannot use utf8 in your content). If you don't do this you are probably not gaining anything by having your site as utf8. As an aside, you should also indicate to browsers that the site is utf8, which you can probably do most easily with <meta http-equiv="content-type" content="text/html; charset=UTF-8" />. This is only touching on the topic briefly as github issues are not really the place for this (forum coming soon!) and I suspect this warrants a page in the forthcoming documentation.

The only place where I can see modx/clipper possibly not being 100% right is in DocumentParser::stripTags(), though I'm not convinced. Although that function currently does not use explicitly multibyte functions, it is only operating on characters in the ASCII subset of utf8, which should mean that they will be implicitly, in this case, multibyte safe.

-- Tim.

**Comment by MPerrine** [comment]
**show variables like 'char%';**
character_set_client    utf8
character_set_connection    utf8
character_set_database  latin1
character_set_filesystem    binary
character_set_results   utf8
character_set_server    latin1
character_set_system    utf8
character_sets_dir  /usr/local/mysql-5.5.9-linux2.6-x86_64/share/chars...

**show variables like 'collation%';**
collation_connection    utf8_general_ci
collation_database  latin1_swedish_ci
collation_server    latin1_swedish_ci

**show full columns from modx_site_content;** shows collation in latin1

I don't know how to change this configuration on my server. And I'm running Evo on the same server without having such problem. It sounds weird... but by now, the problem stopped occuring !

**Comment by TimGS** [comment]
I'll close this issue then.

Note that your char/collation settings are not ideal, but this really isn't the best place to discuss this - the MySQL forums or MySQL documentation will be better and probably more informative. At some point I'll write something myself on character sets, but I won't be saying anything that isn't on the MySQL site anyway.
