### ISSUE TITLE
keep-session-alive.js and mootools

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#231]
There is a comment 'TODO: update session_keepalive to return {"status":"ok"} once mootols is removed'

Presumably this means more to @Cipa than it does to me?!

**Comment by Cipa** [comment]
I have to look at this in more detail(maybe change the way keep session alive works) and I don't have the time right now. Can this be postponed until 1.3?
It's not a big issue and we can remove the comment if you want.

**Comment by TimGS** [comment]
What's it do? Why is {"status":"ok"} better?

Will anything not work at the moment?

**Comment by Cipa** [comment]
I think what I wanted to implement is something like this
From
sessionResponse != '{status:"ok"}'
to
sessionResponse.status != 'ok'

{status:"ok"} not being a valid JSON string I don't think it's possible. Currently the return is just tested as a string not as a JSON object. In order to do the above /session_keepalive.php needs to be modified to return a valid JSON object

This should be an easy fix but needs to be tested, I might have time later this moth or next month.

**Comment by TimGS** [comment]
OK - so everything works fine as it is then?

**Comment by Cipa** [comment]
Yes, it's not a bug, it's a comment to improve the code

**Comment by TimGS** [comment]
OK, I'll close it then. Fix whenever you want, if you want.
