### ISSUE TITLE
image type tv with kcfinder when Clipper is installed in a sub folder

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#260]
When selecting an image for a image type tv the path includes the sub folder when updating the path. 

E.g. if Clipper is installed at /clippercms path for tv image ends up as:

/clippercms/assets/images/logo.png

Then the preview image ends up as: DOMAIN/clippercms//clippercms/assets/images/logo.png

and so does not display. It works fine for mcpuk.

**Comment by Cipa** [comment]
Is this for the develop branch, cause I can't reproduce it?
On my local server when I insert an image I get the correct path and clipper is installed in a folder

**Comment by microcipcip** [comment]
I can't reproduce it either. I have installed ClipperCMS Develop in a sub-sub folder, then I have added images from both TVs and TinyMCE and they all return the right path. I have tried with Friendly URL turned off and on. I remember that I have encountered this issue before, but it was fixed by Tim. 

Are you using the latest ClipperCMS Develop? Or is this a version you've installed before? If this is the latest version, please provide your server configuration settings.

**Comment by bossloper** [comment]
Hmmm, looks fine now. I can only put it down to an old code version. I updated to the latest dev last week.
Sorry guys.
