### ISSUE TITLE
AjaxSearch Minimum characters

### ISSUE THREAD

**Issue by nick0** [ClipperCMS/ClipperCMS#28]
I would love an AjaxSearch Minimum characters default of 2 instead of 3.

I have built a number of sites where valid search terms were 2 characters (eg SA, NT, KI etc) .

To change the min characters from 3 to 2, a couple of php files need to be "edited" which makes it trickier to keep track of during upgrades:
- "classes / ajaxSearch.class.inc.php"
- "configs / default.config.php"
  (not sure why it is doubled up in 2 files??)

It would be great if a minimum of 2 could be controlled from the snippet call with &minChars=`2` rather than having to edit core files for it to work.

**Comment by TimGS** [comment]
I haven't use AjaxSearch for a long time as I have my own alternative, but surely &minChars should work.

Can you also document where the edits to those files have to be made. Much as we like puzzles, we also have limited time ;-)

Do these edits force &minChars to 2 or are they a full fix so that &minChars still defaults to 3 but can be changed to 2 via &minChars? 

If you have - as appears to be the case based on your post - found a bug, and perhaps know the solution, could you submit a patch via github?

thanks,
Tim.

**Comment by Coroico** [comment]
Hi Guys, AjaxSearch is still maintened by myself. So I could provide a version 1.9.3 with some fixes and the 2 chars minimum length feature.

**Comment by TimGS** [comment]
@Coroico - that would certainly be appreciated. Thanks!

**Comment by nick0** [comment]
@TimGS - I think the hack that I was doing forced &minChars to 2 - but enabled &minChars=3 to work when specified in the call and work as expected. Without that hack, &minChars=2 never worked in the snippet call. 

My thinking is that the default can remain at 3 but that &minChars=2 should work when specified in the snippet call. Alas I am not a coder and have no idea how to submit a patch.

@Coroico, Thanks, that sounds awesome! Could you leave the default at 3 as is but allow &minChars=2 (eg less than the default) to work when specified in the snippet call?

**Comment by TimGS** [comment]
Closed. Opening a new issue to upgrade AjaxSearch to 1.9.3 for ClipperCMS 1.1.
