### ISSUE TITLE
Minor CSS issue in manager

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#295]
On Create/Edit template, could the first five inputs/selects be of matching width? Includes:

Template name:  
Description:  
Existing Category:  
New Category:  
Default child template:

"Restrict child templates:" can probably stay as is - it's only yes/no.

A similar issue exists for Create/edit Module, and also for Create/edit Chunk.

**Comment by Cipa** [comment]
I had a look at the code and it seems like there some hardcoded styles for these fields both in css and html. The way I see this working is to remove these specific styles and let the fields inherit the default width. Also for drop-downs I recommend using their default width based on the width of the options, otherwise you end up with 'width: 313px' in your css.

I also attached 2 screenshot one from Chrome and one from FF and I think the css needs some more work. First the height of the input fields is different + the dropdowns seem to use the default style of the OS.

Not sure when this should be done and how it will break the existing code but I think that
- remove inline widths for input
- remove specific css widths(most of them anyway)
- remove inline or specific css widths for selects(most of them anyway)
- consistent input height for all browsers
- consistent select height for all browsers
- visibility:collapse for Child templates section should be switched to display:none as it doesn't work in chrome

![screen shot 2013-06-15 at 8 54 18 am](https://f.cloud.github.com/assets/293377/658111/516726c4-d5bb-11e2-8fa1-9c98381dab8e.png)
![screen shot 2013-06-15 at 8 54 26 am](https://f.cloud.github.com/assets/293377/658112/5171cdc2-d5bb-11e2-8dfd-3d28bd46b12b.png)

**Comment by microcipcip** [comment]
It is difficult to have the same lenght for all fields because when you change the width in one page it is changed in other pages too. 

I think we can delay this until we remove the tables and we have a proper layout in place. There are a lot of inline css rules and the tables are a mess to work with.

**Comment by TimGS** [comment]
Can you come up with an interim solution for 1.2, in the next few days?

Remove any inline styles you need to! The height issues are not good and should be fixed for release. Width issues are desirable to fix, but IMHO not essential.

-- Tim.

**Comment by Cipa** [comment]
Will try

**Comment by TimGS** [comment]
Ta. 

I've fixed the visibility:collapse issue in https://github.com/ClipperCMS/ClipperCMS/commit/2b5615b59b649b50f2f30ebcd9e6e54707250c00

**Comment by Cipa** [comment]
I've been looking and trying to fix the css for 2 hr now and I fear there will be a lot of changes. I will also have to do some IE tests. Are we supporting IE8?

**Comment by TimGS** [comment]
OK - that's sounding like too much work and too many changes for inclusion in 1.2.

We probably ought to support IE8. I don't think IE9 will work on some older but still widely used incarnations of Windows.

I think the main visual issue is the thin select boxes on Chrome. Is this feasible to fix in a reasonable amount of time and with minimal coding? Use JS if necessary. If it's still an undue amount of work, let's just postpone the issue till 1.3.

As per your recommendation above I agree it may be best to let the select boxes be their 'natural' width.

**Comment by TimGS** [comment]
PS. Do whatever you think best - if this means postponing the entire issue till 1.3, then that's what we will do.

**Comment by Cipa** [comment]
I think I figured out the best way to fix the css issues but I will need some help in testing the manager for any inconsistencies. Depending when you want to launch and depending what you want for 1.3(are we switching to the new interface?) we can do this now or later

So far, this is the plan
- remove hardcoded html-css widths
- use a css solution for [\* tags. I use :after and :before and I think it's a good solution. 
- Remove code like this: `<span style="font-family:'Courier New', Courier, mono">&nbsp;&nbsp;</span>`
- Test

Mostly this effects the elements interface and maybe the create/edit resource interface.

I hope to finish today

**Comment by TimGS** [comment]
I have merged https://github.com/ClipperCMS/ClipperCMS/commit/87981ccb23fe349988e18cf8794e4d4900f5421b for 1.2. Closing the issue as the remaining issues for 1.3 are part of the more general modernising of the manager, especially as regards eliminating inline styles.

Thanks.
