### ISSUE TITLE
Wayfinder odd and even classes would be nice

### ISSUE THREAD

**Issue by nick0** [ClipperCMS/ClipperCMS#30]
I remember hearing about this in one of the beta releases but it's not in the 1.0.6 release

**Comment by TimGS** [comment]
In general, new feature proposals should now be discussed at http://www.clippercms.com/forum/feature-requests/

However given that this is more of a tweak than a new feature, we would probably accept a secure and functional patch from a community member subject to it following our coding guide.

In the meantime you could use &rowClass and in your CSS use .row1, .row3, .ro5 (etc).

**Comment by nick0** [comment]
Ok Thanks Tim, posted in the forum

**Comment by TimGS** [comment]
In addition to the above workaround, there are Javascript solutions for ie7 and ie8 (which do not support CSS n'th child); see Google.

I'm marking this as wont fix, but only because it's not a priority for the core team. However I don't think anyone would object to a community submitted patch for this.

-- Tim.
