### ISSUE TITLE
date TVs should save date as unix timestamp (discussion?)

### ISSUE THREAD

**Issue by Cipa** [ClipperCMS/ClipperCMS#353]
Currently the TV dates are saved in db as a string like "01-03-2012 10:15:00"

This is neither a mysql valid date neither a php date. We should switch to either a format like

2003-12-31 01:02:03
OR
unix timestamp

We can force the save to be a unix timestamp(or something custom) by using a plugin but would be nice to have some consistency.

Thanks

**Comment by TimGS** [comment]
All TV values are strings, so the question is as to what format we use for this _string_.

As the values are currently dates - not timestamps - I suggest that whatever is chosen should be just that - a date, not a timestamp. Changing to a unix timestamp fundamentally changes the nature of the TV type. That's not to say we could not consider adding a timestamp TV type - but we shouldn't effectively remove the date/datetime type.

I can see advantages to using the SQL format - but we should consider existing code and backwards compatability. It may well be best to add another date TV type, and to deprecate the old one.

**Comment by Cipa** [comment]
From a sorting point of view, in custom mysql queries, a unix timestamp works really well so string is fine in this case. 

If we save as mysql date format, we probably need a date field or tell the query that the string fields should be handled like a date which is not ideal. I'm not sure what are the advantages of using mysql date format but I personally like the simplicity of the unix timestamp

Instead of creating a new date TV maybe we could show a dropdown to allow users to select how to save data in the db: default/unix timestamp

**Comment by TimGS** [comment]
There are a couple of issues that are effectively fixed, as per my above comment. To elaborate...

1) TV values are _always_ stored in the db as strings. This is fundamental to the MODx/Clipper schema - without a significant rewrite of arguable worth and involving currently unfeasible time overhead this is unlikely to change in the near future. Such a rewrite would not simply change the schema - that would be the least of the jobs involved - but would require all the API functions regarding TVs to be rewritten (and tested!) and any old code accessing these TVs may need to be updated (and also tested!). I can think of ways of going about this that would minimise the latter issue, but the size of the this job should not be understated.

As such, discussing the value of MySQL date fields is academic. Undoubtably they are better than strings for storing dates, but this is missing the point as to how TVs - which are multi-purpose entities - are stored.

2) Unix timestamps are not dates. A unix timestamp is a fixed point in time measured in seconds, not including leap seconds, since the start of 1st Jan 1970. For a fixed point in time it is identical, wherever in the world you are. If I arranged to phone you at 1376688048 unixtime, it may be an odd way of going about things, but it would work. A MySQL date or datetime is a 'calendar' date, and is not fixed on a global basis - it contains no timezone element. 'My' 6pm on the 15th August 2013 is not the same as everyone else's. If for example you live in North America, it will be some hours before 'your' 6pm on the 15th August 2013. If I was to arrange to phone you, we would have to consider timezones - but MySQL dates have no timezones, so they are inadequate for specifying fixed points in time.

As such, dates are simply not timestamps. Treating one as the other is probably fine (though less than advisable) if you deal with only one timezone, but lays the foundations for confusing bugs and pitfalls if you have more than one timezone. Even if you deal with one timezone but have daylight saving in summer, there are pitfalls to using the two data types interchangeably.

That is not to say a timestamp TV type would not be useful (I would completely support the introduction of such a TV type) - but it is to say that 'converting' a date TV type to a timestamp amounts to removing the date type and introducing a new _and different_ timestamp type.

It also may be wise to _consider_ deprecating the existing date TV type and introducing one that used a 'MySQL style' string format - it could make coding easier.

**Comment by Cipa** [comment]
If anyone is interested I created a custom Tv that does this but it's for 1.1.3 and should work for MODX Evo as well. 
https://github.com/Cipa/unix-timestamp-date-tv

I use it to save unix timestamp values so I can easily do a sort by date in my custom sql

**Comment by TimGS** [comment]
Can you make a 'proper' native timestamp TV? Visually in the manager it could be much the same as a date TV, but (perhaps?) with a timezone picker defaulting to the current timezone. Internally storage would be as  a unix timestamp (albeit in a string) and conversion from the inputted date would take into account the selected timezone.

Any output widget would probably just use the current timezone - alternatively and perhaps more easily an output modifier could be used. I was considering proposing adding a date formating output modifier to 1.3 - this could easily detect whether a TV contained a date value or a timestamp and act appropriately.

**Comment by Cipa** [comment]
The main reason for changing the date format here, at least for me, is the possibility to sort from a sql query(do you see other use cases?).
Seems like both timestamp and mysql date are "sortable" when they are set as strings in the DB. The current format is not.

If we are going to use a timestamp there is a gmdate php function we could use. If the date is properly decoded we should be ok with timestapms, but it looks like it's more complicated than using a mysql date format.

**Comment by Cipa** [comment]
> Can you make a 'proper' native timestamp TV?

Maybe we should do this after we switch to the html5 input date fields. I'm not sure how backwards compatible will the html5 dates be.

> timezone picker ?

Is this really needed? I'm not too familiar with building sites for different time zones.

**Comment by Cipa** [comment]
What do you think about the createdon. editedon fields? They are saved as unix timestamps.
Shouldn't we be consistent?

**Comment by TimGS** [comment]
We can sort HTML5 dates first, though it's probably not a big deal.

A timezone picker is not needed if you can assume the time refers to the current server timezone (or alternatively you could try using the client timezone - which IIRC is harder to do reliably but _may_ be what is required). However I can't help thinking that if the timezone is not important, you _may_ actually be best with a date/datetime, not a timestamp.

Generally if a point in time is genuinely adequate to express in human language without resort to a timezone, it probably should be (in the SQL sense) a date/datetime (unless perhaps the lack of timezone is because you only ever deal with one timezone, in which case things can be a little more ambiguous).

If however you need to pin down a fixed invariant point in time, you need a timestamp - and to pin down a fixed point in time, a date without a timezone is inadequate.

For example, the time of a software compilation should be a timestamp - you need to know which edits to the source have reached that particular build. It's a fixed point in time, as are the times of the edits to the various source files.

For an example of a date, consider a society with annual paid membership, for which the subscriber receives a quaterly newsletter and free admission to society events - they would probably need a date field to hold the expiry date of a member's subscription. A timestamp would be inappropriate as it would make no sense to pin down the expiry of membership in this context to a specific point in time. You are more likely to cause confusion by doing so.

Perhaps we need two timestamp TVs - one with a timezone picker, one without? I would say one TV would be better with an option to have a timezone picker or not - but there is currently no facility in the db schema for UI options and I'm reluctant to suggest adding another field to the schema for just one TV type.

**Comment by TimGS** [comment]
There is no issue with consistency re: createdon/editedon. They are fixed points in time and any ambiguity cannot be allowed - hence they are unix timestamps. The only questionable aspect of the schema is that they are actually stored in MySQL in an integer column instead of using a timestamp column - but that's what we have and it's probably more prone to pitfalls to change it than leave as is.

Consistency does not involve using the same internal data type for data which is fundamentally different. That's like saying everything should be stored as a string.

**Comment by TimGS** [comment]
re: sortability. Yes, the current date format is not the best for this and many other reasons regarding queries. But that is no reason to change it into a format that is inappropriate for the data in question. No matter how much discussion we have on this, a MySQL date or datetime is not a unix timestamp; they are not generally interchangeable and never will be!

What would be useful, as above, is
a) A timestamp TV to be added. We currently have no timestamp TV - once again, this is not a date field, it would be a timestamp!
b) consideration of a different format for the date TV as you are quite correct to say that the present format is not the best. I suspect just changing it would break existing software with no feasible workaround aside from rewriting existing software - which in my view is not good enough. Hence my suggestion to deprecate the current date TV and introduce a new one.

**Comment by Cipa** [comment]
I was referring to consistency from a time zone point of view. 

So for the new TV all we have to do is change the output format to use mysql date format. Should be easy.
If we do b) why is there a need for a). What do you think would be a good name for the new Date TV

**Comment by TimGS** [comment]
createdon/edited are suitable as timestamps as they fixed points in time. Timezones are not relevant in these cases _except_ when converting from the timestamp to a human readable output suitable for screen display. The server timezone will currently be used, as it will for most, if not all, dates and times in the system. Since 1.2 the server timezone can _optionally_ be overridden and the timezone can be set in the config file - see the installer.

(a) and (b) are solutions for two _different_ types of data. Again, see above regarding timestamps and dates/datetimes. See also Google. The MySQL forums will no doubt have plenty of discussion as will stackoverflow. I can't really add any more without going round in circles and it's all been said elsewhere anyway. I realise your own motivation is to - quite reasonably - be able to more easily sort dates in SQL, and as such either a timestamp _or_ a 'mysql' date format will solve your own issue, but there is much more to dates, times, and timestamps than this. Saying one will do the job of the other is like saying integers and floats are interchangeable - well they might be (i.e. if your floats happen to be whole numbers) but in the more general case they are not.

Regarding output format, I don't think the MySQL format would be generally appropriate as it all depends on the date format a _human_ would expect to read - which depends on both context and locality. Adapting the existing date widget so that it can automatically use date values in both the legacy and new 'mysql' format would be much better. Similarly I will ensure any date formatting output modifier can handle either date format.

**Comment by TimGS** [comment]
Regarding a name, I honestly don't know.

Maybe just 'Date2'? Inelegant, but it's only seen by developers.

Maybe 'SQLDate'?

**Comment by Cipa** [comment]
I was looking into this and I don't think we need a need a new tv type. The same thing can be achieved from the configuration/Interface & Features/Date format. If we provide an option like yy-mm-dd and make it default for new installs we should be ok.
The time format is already correct.

The only problem with this that the dates will not be saved to the db in mysql format if the configuration is not correct and also some people might like to display dates differently like in a french format which I don't think is advisable anyway. In order to overcome this we need a hidden field or some html custom attribute.

By looking into this I found a bug. Seems like the publish date and created on date don't work if the format is changed. I will probably create a new issue once I find more about it.

**Comment by Cipa** [comment]
Well the bug was because there are more files that need to change when a new date format is added. See toTimeStamp and toDateFormat function in documentParser file. The new date format might have to be "registered" in other places as well.

So what could work is add this new date format "yy-mm-dd" make it default, change all the the files that are using dates to recognize this new format even the DOB fields for users and later on if anyone wants to sort by this field they can do so easily from MySql with something like ORDER BY CAST(SDate DATETIME);

I assume this will probably the way the dates will be saved when we switch to html5 format.

Edit:
DOB is saved as a unix timestamp, so no sql date format in for this unless we want to change the table structure.

Edit 2:
Maybe we can even remove all the other date/time formats and have just the ISO/MySql format.

**Comment by TimGS** [comment]
re: DOB. This is not a great situation - a date should be a date (unless for some reason you want to pin down the exact moment in time someone was born - but I doubt very much if this was either the intention or a likely use). I suspect that we are probably best leaving as is for the moment, but it could give rise to MySQL's DATE(dob) or PHP's equivalent being a day out if the server timezone was changed or if the db moved servers and the new server was running with a different timezone.

re: Formats. Yes - I already know of a couple of places where core code expects either dd-mm-yyyy or yyyy-mm-dd as a TV's date format. In the cases I know of a fallback is present in the form of strtotime() but I think in the places you mention this doesn't exist. I agree that we should encourage the use of yyyy-mm-dd (this is erroneously referred to as yy-mm-dd in existing code comments and in how the core handles the date format option - all mentions of 'yy' are actually handled as 'yyyy'). This has already been covered in the previous discussions re: HTML5, but there appears to have been in the past conflation of date _storage_ format with date _output_ format. I agree with you that new installations should have yyyy-mm-dd as the default date _storage_ format - unfortunately I suspect that for backwards compatibility we may have to keep and support the dd-mm-yyyy option, but deprecate it.

**Comment by Cipa** [comment]
From a jquery ui date point of view date format is: yy-mm-dd so yyyy is wrong(?).

I was looking a the datetime implementation in browsers and it seems like support is not there yet. http://caniuse.com/#search=datetime. Only opera seems to have the datetime implemented.

Maybe we should keep jquery ui date for now, add this new yy-mm-dd date format make it the default one.
Additionally we could only use one format(remove date and time formats from the config section) and code something that will convert the dates from old installs into this new format.
This can be done at upgrade by parsing the date TVs or when a resource is edited;on save the new format will be saved into the db.

**Comment by TimGS** [comment]
YYYY is usually used to denote a four figure year. YY is usually used to denote a two figure year. I've rarely come across anything different - the MODx/Clipper config option is here the notable exception. I can't comment about jquery-ui, but using YY to denote a four figure year is misleading for obvious reasons. If jquery-ui does something different, that doesn't make the usual convention wrong, it means that jquery-ui are being misleading. Please can we refer to four figure years and two figure years in the generally accepted way.

re: HTML5 date support. We've had this discussion before! It's OT for this issue - if it is to be re-discussed can we use the forum.

To summarise the date TV issue so far:
1) _All_ TVs are always stored as strings.
2) There is a date TV but no timestamp TV.
3) The default date format as stored in TV strings is dd-mm-yyyy (misleadingly referred to as dd-mm-yy in the config option).
4) yyyy-mm-dd is also supported and is viewed as a better option for more than one reason.

Ways forward:

1) On upgrade convert date TVs in the dd-mm-yyyy format to yyyy-mm-dd.

This is all well and good for the TV data, but if any bespoke code assumes the former option it breaks. As such I would say this is not an option.

2) Make yyyy-mm-dd the default for new sites. Do not change old sites on upgrade.

No problems here - as far as I can see yyyy-mm-dd is already supported throughout the core code.

3) As for (2) but deprecate the dd-mm-yyyy format.

No coding changes compared to 2 - though being realistic I don't yet see any undue problems in maintaining support for the old format.

I'll close this issue as it's done well and truly beyond the original topic, and has split into multiple issues relating to dates. I will open an issue for the default date format.

thanks,
Tim.
