### ISSUE TITLE
login processor rewrite.

### ISSUE THREAD

**Issue by TimGS** [ClipperCMS/ClipperCMS#50]
Needs revising to be able to use the DBAPI.

Currently is the only file in processors (apart from the two class files) that is accessed directly and not via manager/index.php. This probably needs revising as it is likely to cause other problems in addition to the DBAPI issue.

**Comment by kp52** [comment]
Suggestion: move include command for settings.inc.php in login processor to somewhere after the point where the $modx object is created (currently line 52), so that dtabase access can be via the API. I haven't found anywhere between the current position and the proposed one that involves using settings that are read when settings.inc.php is included.
