### ISSUE TITLE
Enhance Wayfinder by adding includePrivates option

### ISSUE THREAD

**Issue by bossloper** [ClipperCMS/ClipperCMS#59]
I have found this quite useful:

http://forums.modx.com/index.php/topic,27054.msg164395.html

... to allow a wayfinder menu to list a private resource page in the menu. Thus when not having access it takes you to the system 'unauthorized page', i.e. probably the site login page.

**Comment by TimGS** [comment]
This is probably one for discussion in the forum. http://www.clippercms.com/forum/feature-requests/

There are a few Wayfinder requests now. It's probably not going to be a priority for the core team though, so what it probably needs is someone in the community to either fork Wayfinder or liase with the original author.

**Comment by bossloper** [comment]
OK I will add it there so it is logged.

I have another Wayfinder related one too, more of a bug, as the text for menu titles, descriptions etc is not encoded.

**Comment by TimGS** [comment]
re: entity encoding...

Most snippets do not encode quotes (etc) as entities, unless you use phx, which would be rather laborious and maybe not even possible in some cases.

My solution, which is less than ideal, is to have a plugin encode these fields when a document is saved. It is less than ideal as when you edit a document you see the entities, plus I do think that raw text should be stored, not output. The former issue could be solved by either another plugin or modifying the manager.

Certainly the issue is more than just Wayfinder. It could probably do with discussion in the forum to see what solutions people have come up with already.
