### ISSUE TITLE
Paginated List (Ditto) call still affected by PHx

### ISSUE THREAD

**Issue by kp52** [ClipperCMS/ClipperCMS#75]
Tested a paginated List call with PHx installed as plugin in latest Clipper download, to see if changes to chaching have altered anything. 

Result: behaviour concerning caching is the same as in MODX 1.0.6, i.e

**Pagination only works when List call is cached and page is non-cacheable**

If List is called uncached, placeholders are not populated. 
If List is called cached with page cacheable, placeholders are populated, but only cached version of the page is displayed when a link to another page is clicked

Test environment:
Clipper download ClipperCMS-ClipperCMS-v1.0.6-pl-153-gf2e0dd6.zip
Windows 7 PC + PHP 5.3.17 + Apache 2.4.3 + MySql 5.1.34-community-log

**Comment by TimGS** [comment]
I suspect the issue lies in phx. If anyone wants to investigate it more then any info gratefully received.

Before spending much time on this you may want to check the functionality in the placeholders branch. It contains output modifiers similar to some in phx, but no conditionals. I don't intend implementing conditionals - I think they would be better in snippets. You may decide you don't want phx anymore anyway. I'm hoping this will make it into 1.2.

Another issue is that if anyone modifies phx they either need to accept they are forking it and taking on maintenance of the fork, or they should contact the author to see if they are still developing it themselves.

In the meantime I'll close this issue.

thanks,
-- Tim.
